Sous Chefs Adoption
sous-chefs/motd-tail pull request #28
Opened 2021-02-22 23:58 UTC by EMH333

# Description

Adopt into Sous Chefs

## Check List

- [ ] All tests pass. See TESTING.md for details.
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable.

2021-02-25 00:24 UTC, ramereth requested changes

2021-02-25 00:24 UTC, ramereth commented on CHANGELOG.md
> +- Cookstyle fixes
Also add `Sous Chefs Adoption`

2021-02-25 00:24 UTC, ramereth commented on kitchen.dokken.yml
> +      pid_one_command: /sbin/init
```suggestion
      pid_one_command: /usr/lib/systemd/systemd
```

2021-02-25 00:24 UTC, ramereth commented on metadata.rb
>  supports 'ubuntu'
Please add all the RHEL/CentOS derivatives as well.

2021-02-26 23:54 UTC, ramereth approved these changes

2021-02-26 23:54 UTC, merged

2021-02-26 23:54 UTC, kitchen-porter commented
Released as: [5.2.0](https://github.com/sous-chefs/motd-tail/releases/tag/5.2.0)